using UnityEngine;

public class CameraBillboard : MonoBehaviour
{
    [SerializeField] Transform mainCamera;
    public bool isEnabled = true;
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        if (!isEnabled) return;
        Vector3 direction = mainCamera.position - transform.position;

        // Y²¬•ª‚ğœ‹iã‰º‰ñ“]‚È‚µj
        direction.y = 0;

        // Y²‚Ì‚İƒJƒƒ‰•ûŒü‚Ö‰ñ“]
        if (direction != Vector3.zero)
        {
            Quaternion targetRotation = Quaternion.LookRotation(-direction);

            // Œ»İ‚ÌY²‰ñ“]‚Ì‚İ•Û
            transform.rotation = Quaternion.Euler(0, targetRotation.eulerAngles.y, 0);
        }
    }
}
